### ISSUE TITLE
[Feature]: Add Google Image Search feature similar to Unsplash #5

### ISSUE THREAD

**Issue by drtobbyas** [inovector/MixpostApp#14]
It would be great if you could add the ability to use Google Image Search when adding media.

From experience, Google Image Search provides better search quality and semblance to search terms than Unsplash.
Unsplash is more suited for Stock Photos which most times do not relate to or convey the message you are trying to post.

Even though Google is a general-purpose Search Engine, Google Image Search returns good enough images that can be used for Twitter and other Social Media posts.

This is useful, especially for tech-related search terms for instance, if you search 'Kubernetes or Gitlab' in Unsplash, you will probably get unrelated Stock Photos or nothing. Google wins in these scenarios

Most times I have to do a Google search, find the image, download and upload to MixPost. Integrating Google Image Search can greatly improve this workflow.

**Comment by lao9s** [comment]
Hi,

I do not plan to integrate Google Image Search.
