### ISSUE TITLE
I get an error when I start mixpost_horizon:*

### ISSUE THREAD

**Issue by jowis** [inovector/MixpostApp#3]
Hello everyone,

I am trying to install mixpost Little, but while configuring Supervisor I get the error message `mixpost_horizon: ERROR (spawn error)` when I run `sudo supervisorctl start mixpost_horizon:*`.  I have created the `mixpost-horizon.conf` file in the `/etc/supervisor/conf.d` folder as indicated in the [documentation page](https://docs.inovector.com/books/server-configuration-mixpost/page/installing-configuring-supervisor#bkmrk-configuring-supervis) with the following text:
```
[program:mixpost_horizon]
process_name=%(program_name)s
command=php /path-to-your-project/artisan horizon
autostart=true
autorestart=true
user=joel
stopwaitsecs=3600
```

What should I do?

Many thanks in advance.

**Comment by lao9s** [comment]
Hi @jowis 

Did you install Redis?

**Comment by jowis** [comment]
Hi @lao9s 

Yes, I installed Redis. I also installed php8.1, MySQL, apache web server, composer,  and activated mod_rewrite and executed "composer create-project inovector/MixpostApp"

Thanks for your time,

Joel

**Comment by lao9s** [comment]
Please, check the logs at `your-project/storage/logs/laravel.log`

And send here

**Comment by lao9s** [comment]
@jowis did you manage to install it?

**Comment by jowis** [comment]
Hi @lao9s 
Thanks for your attention. I don't know where to find the logs on my computer. I may not have done the right installation because I have browsed to see if there is any "your-project" folder, but I don't see any. I've found a folder "/var/www/your-mixpost-project" with only an empty folder "public" .

**Comment by lao9s** [comment]
`your-project` is not a real folder, this is supposed to be your project/folder name. For example: `github-website/storage/logs/laravel.log`
