### ISSUE TITLE
Missing step in Readme Documentation

### ISSUE THREAD

**Issue by izdrail** [inovector/MixpostApp#4]
I was trying to install this skeleton manually 
I think is missing the step of 
```
php artisan vendor:publish
```
Before the php artisan migrate

**Comment by lao9s** [comment]
Hi @cornatul 

That's because you missed this step `composer create-project inovector/MixpostApp`. When you execute this command, the script will run all the necessary commands.

```
 "post-create-project-cmd": [
            "@php artisan key:generate --ansi",
            "@php artisan mixpost:setup-gitignore",
            "@php artisan queue:batches-table",
            "@php artisan mixpost:publish",
            "@php artisan storage:link"
        ]
```

The documentation is compatible only with this command `composer create-project inovector/MixpostApp`.

**Comment by CodeShakingSheep** [comment]
Ran into the same issue. It's not enough to just run `composer create-project inovector/MixpostApp` as `php artisan mixpost:publish` is not the same as `php artisan vendor:publish`. 

Without `php artisan vendor:publish` Mixpost DB tables are not being created leading to a HTTP 500 error after logging in with the first user.

Could solve it by running `php artisan vendor:publish` first and then `php artisan migrate` as @izdrail suggested.
