### ISSUE TITLE
Can't open mixpost

### ISSUE THREAD

**Issue by gummipunkt** [inovector/MixpostApp#6]
I've installed mixpost as standalone app. The new folder is "mixpostapp", so I opened 

`https://domain.tld/mixpostapp
`
-> nginx output "403 Forbidden"

Then I opened 

`https://domain.tld/mixpostapp/public`

here it forward to

`https://domain.tld/mixpostapp/public/mixpost`

-> nginx output "404 Not Found"

Any suggestions?

**Comment by lao9s** [comment]
@gummipunkt try this: https://domain.tld/mixpost/, without `/public`.
You may instruct Nginx as the default public web root. You should set the default public web root to the "/public" folder of the Mixpost Standalone project.

**Comment by gummipunkt** [comment]
Thanks, already tried that:
```
/var/www/web/mixpostapp/public$ ls -la
total 28
drwxr-x---  3 web27 client1 4096 Jan 29 10:11 .
drwxr-xr-x 14 web27 client1 4096 Jan 29 10:13 ..
-rw-r--r--  1 web27 client1    0 Jul 12  2023 favicon.ico
-rw-r--r--  1 web27 client1  603 Jul 12  2023 .htaccess
-rw-r--r--  1 web27 client1 1710 Jul 12  2023 index.php
-rw-r--r--  1 web27 client1   24 Jul 12  2023 robots.txt
lrwxrwxrwx  1 web27 client1   64 Jan 29 10:11 storage -> /web/mixpostapp/storage/app/public
drwxr-xr-x  5 web27 client1 4096 Jan 29 10:11 vendor
web27@xxx:/var/www/web/mixpostapp/public$ 
```

Document Root nginx vhost conf
` root   /var/www/web/mixpostapp/public;`

error log
`2024/02/02 13:56:34 [error] 804901#804901: *199639 openat() "/var/www/web/mixpostapp/public/mixpost" failed (2: No such file or directory), client: ip , server: mixpost.domain.com, request: "GET /mixpost HTTP/2.0", host: "mixpost.domain.com"`

tried to open url
https://mixpost.domain.tld/mixpost

**edit**
when I try to open
https://mixpost.domain.tld/mixpost/

`2024/02/02 14:02:52 [error] 804901#804901: *199676 "/var/www/web/mixpostapp/public/mixpost/index.html" is not found (2: No such file or directory), client:  ip, server: mixpost.domain.com, request: "GET /mixpost/ HTTP/2.0", host: "mixpost.domain.com"`

**Comment by lao9s** [comment]
@gummipunkt 

It is very difficult for me to understand what you are doing and why you are getting such strange errors. I tested the installation and everything works fine.

From what I can see, you don't have the `public` folder in the root folder.

I can help you with the installation for a fee. Please, contact us through the chat on mixpost.app website.

**Comment by gummipunkt** [comment]
@lao9s Sorry, I've already figured out what the problem is. You expect a apache webserver to handle the .htaccess in the public folder, I missed the file, don't know why. Sorry.

So I've rewritten it for my nginx conf 

```
if ($http_authorization ~ "."){
	set $rule_0 1;
}
if ($rule_0 = "1"){
	set $http_authorization $http_authorization;
}
if (!-d $request_filename){
	set $rule_1 1$rule_1;
}
if ($uri ~ "(.+)/$"){
	set $rule_1 2$rule_1;
	set $bref_1_0 $1;
}
if ($rule_1 = "21"){
	rewrite ^/ /${bref_1_0} permanent;
}
try_files $uri/ $uri /index.php$is_args$args;
```

Now everything works fine.
